### ISSUE TITLE
Script to download finished artifacts

### ISSUE THREAD

**Issue by nedbat** [ogrisel/python-appveyor-demo#25]
I wrote a Python program to download all the artifacts from the latest Appveyor build: https://bitbucket.org/ned/coveragepy/src/d14e44a86376ec95645584360501ab5afc70d26f/ci/download_appveyor.py?at=default

Maybe others will find it useful.

**Comment by jayvdb** [comment]
A very similar script also at
https://github.com/ionelmc/python-lazy-object-proxy/commit/967e3837500bc382269f4e9e8bca351044712e96

**Comment by ogrisel** [comment]
I think it would be useful to submit one of those a as a PR for inclusion to the repo along with a new section to the README.md to explain the use cases for this script.

**Comment by ankostis** [comment]
Why not use [*twine*](https://pypi.org/project/twine/) to push artifacts to [*PyPI*](https://pypi.org/) whenever the commit is tagged?

**Comment by ankostis** [comment]
Why not use [*twine*](https://pypi.org/project/twine/) to push artifacts to [*PyPI*](https://pypi.org/) whenever the commit is tagged?

Continuing my suggestion above about twine, 
this is a sample `appveyor.yml`:

```yaml
environment:
  PYPI_USER: "FOO"
  PYPI_PSWD:
    # See https://www.appveyor.com/docs/build-configuration/#secure-variables
    secure: <paste_your-encrypted-value>

#... regular build here

on_success:
  - ps: >-
      $cmtid = git rev-parse HEAD
      if (git describe --exact-match $cmtid) {
        twine upload -u PYPI_USER -p PYPI_PSWD dist/*
      }
```

Of course the situation becomes a bit more complex if gpg-signing is needed.
